[http]
host = "127.0.0.1"
port = 8000

[database]
url = "postgres://academy@127.0.0.1/academy" # https://docs.rs/tokio-postgres/latest/tokio_postgres/config/struct.Config.html
max_connections = 10
min_connections = 0
acquire_timeout = "10s"
idle_timeout = "10m"
max_lifetime = "30m"

[cache]
url = "redis://127.0.0.1:6379/0"
max_connections = 10
min_connections = 0
acquire_timeout = "10s"
idle_timeout = "10m"
max_lifetime = "30m"

[email]
smtp_url = "smtp://127.0.0.1:2525" # https://docs.rs/lettre/latest/lettre/transport/smtp/struct.AsyncSmtpTransport.html#method.from_url
from = "dev@bootstrap.academy"

[jwt]
secret = "changeme"

[health]
cache_ttl = "10s"

[user]
name_change_rate_limit = "30d"
verification_code_ttl = "4h"
verification_redirect_url = "https://bootstrap.academy/auth/verify-account"
password_reset_code_ttl = "4h"
password_reset_redirect_url = "https://bootstrap.academy/auth/reset-password"
newsletter_code_ttl = "4h"
newsletter_redirect_url = "https://bootstrap.academy/account/newsletter"

[session]
access_token_ttl = "1d"
refresh_token_ttl = "30d"
refresh_token_length = 64
login_fails_before_captcha = 3

[totp]
secret_length = 32

[contact]
email = "contact@example.com"

[recaptcha]
enable = false
siteverify_endpoint_override = "http://127.0.0.1:8001/recaptcha/api/siteverify"
sitekey = "test-sitekey"
secret = "test-secret"
min_score = 0.5

[oauth2]
enable = true
registration_token_ttl = "10m"

[oauth2.providers.test]
enable = true
name = "Test"
client_id = "client-id"
client_secret = "client-secret"
auth_url = "http://127.0.0.1:8002/oauth2/authorize"
token_url = "http://127.0.0.1:8002/oauth2/token"
userinfo_url = "http://127.0.0.1:8002/user"
userinfo_id_key = "id"
userinfo_name_key = "name"
scopes = []

[oauth2.providers.github]
enable = false
name = "GitHub"
client_id = ""
client_secret = ""
auth_url = "https://github.com/login/oauth/authorize"
token_url = "https://github.com/login/oauth/access_token"
userinfo_url = "https://api.github.com/user"
userinfo_id_key = "id"
userinfo_name_key = "login"
scopes = []

[oauth2.providers.discord]
enable = false
name = "Discord"
client_id = ""
client_secret = ""
auth_url = "https://discord.com/oauth2/authorize"
token_url = "https://discord.com/api/oauth2/token"
userinfo_url = "https://discord.com/api/users/@me"
userinfo_id_key = "id"
userinfo_name_key = "username"
scopes = ["identify"]

[oauth2.providers.google]
enable = false
name = "Google"
client_id = ""
client_secret = ""
auth_url = "https://accounts.google.com/o/oauth2/v2/auth"
token_url = "https://www.googleapis.com/oauth2/v3/token"
userinfo_url = "https://www.googleapis.com/oauth2/v3/userinfo"
userinfo_id_key = "sub"
userinfo_name_key = "given_name"
scopes = ["openid", "profile"]
