name: build

on:
  push:
    branches: [develop]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: debian-latest
    env:
      USER: root
    steps:
      - uses: actions/checkout@v4
      - run: apt update && apt install -y sudo
      - uses: https://github.com/cachix/install-nix-action@V27
      - uses: https://github.com/cachix/cachix-action@v15
        with:
          name: academy-backend
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          useDaemon: false
      - run: nix build -L --keep-going
      - run: nix build -L --keep-going .#testing
      - run: nix build -L --keep-going .#tests.composite
