name: build

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/DeterminateSystems/nix-installer-action@v13
      - run: nix build -L
      - run: nix build -L .#tests.composite
