name: check

on:
  push:
    branches: [develop]
  pull_request:

permissions:
  contents: read

jobs:
  fmt:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    runs-on: debian-latest
    steps:
      - uses: actions/checkout@v4
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: https://github.com/Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo clippy --all-targets -- -D warnings
