[package]
name = "academy_core_oauth2_impl"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
academy_core_oauth2_contracts.workspace = true
academy_di.workspace = true
academy_extern_contracts.workspace = true
academy_models.workspace = true
