[package]
name = "academy_render_impl"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
academy_di.workspace = true
academy_render_contracts.workspace = true
academy_utils.workspace = true
anyhow.workspace = true
tempfile = { version = "3.13.0", default-features = false }
tokio.workspace = true
tracing.workspace = true
