[package]
name = "academy_render_daemon"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "academy-render-daemon"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
academy_utils.workspace = true
anyhow.workspace = true
axum.workspace = true
clap.workspace = true
clap_complete.workspace = true
tempfile.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
