[package]
name = "academy_core_purchase_impl"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
academy_assets.workspace = true
academy_auth_contracts.workspace = true
academy_core_purchase_contracts.workspace = true
academy_core_coin_contracts.workspace = true
academy_core_heart_contracts.workspace = true
academy_core_premium_contracts.workspace = true
academy_core_premium_impl.workspace = true
academy_core_heart_impl.workspace = true
academy_di.workspace = true
academy_models.workspace = true
academy_persistence_contracts.workspace = true
academy_email_contracts.workspace = true
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
academy_auth_contracts = { workspace = true, features = ["mock"] }
academy_core_heart_contracts = { workspace = true, features = ["mock"] }
academy_persistence_contracts = { workspace = true, features = ["mock"] }
academy_email_contracts = { workspace = true, features = ["mock"] }
