[package]
name = "academy_utils_derive"
version.workspace = true
edition.workspace = true
publish.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
