name: check

on:
  push:
    branches: [develop]
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  fmt:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo clippy --all-targets -- -D warnings

  cargo-nix:
    name: cargo-nix
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix run --accept-flake-config .#generate
      - run: git diff --exit-code

  clorinde:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: |
          for m in academy_persistence/postgres/migrations/*.up.sql; do
            psql -h 127.0.0.1 academy academy < "$m"
          done
      - run: nix run --accept-flake-config .#generate-clorinde
      - run: git diff --exit-code
    services:
      postgres:
        image: postgres:17-alpine
        ports:
          - '5432:5432'
        env:
          POSTGRES_USER: academy
          POSTGRES_DB: academy
          POSTGRES_HOST_AUTH_METHOD: trust
