name: nix

on:
  push:
    branches: [develop]
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'push' && github.actor == 'github-merge-queue[bot]') }}
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - uses: ryanccn/attic-action@v0
        with:
          endpoint: https://cache.bootstrap.academy/
          cache: academy
          # atticd-atticadm make-token --sub github --validity 1y --pull academy --push academy
          token: ${{ secrets.ATTIC_TOKEN }}
      - run: nix build --accept-flake-config -L --keep-going -j1 .#checks
